# Generated by Django 3.0.2 on 2020-01-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('verification', models.CharField(max_length=40)),
                ('street_number', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=40)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.UserType')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.FloatField()),
                ('sex', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Availability')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Breed')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Disposition')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.PetType')),
                ('users', models.ManyToManyField(to='pet.User')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.PetType'),
        ),
    ]
