# Generated by Django 3.0.2 on 2020-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='userPics/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
