# Generated by Django 3.0.2 on 2020-02-27 01:57

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='profile',
            field=models.BooleanField(default=True, verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
