# Generated by Django 3.0.2 on 2020-03-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20200226_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify',
            field=models.CharField(choices=[('N', 'Never'), ('I', 'Immediately'), ('D', 'Daily'), ('W', 'Weekly')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='picture',
            name='profile',
            field=models.BooleanField(default=False, verbose_name='Profile image'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pet.Pet')),
            ],
        ),
    ]
