# Generated by Django 3.0.2 on 2020-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20200125_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
