# Generated by Django 3.0.2 on 2020-01-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20200125_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='pet_type',
        ),
        migrations.DeleteModel(
            name='Disposition',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='pet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('B', 'Beagle'), ('BX', 'Boxers'), ('FB', 'French Bulldog'), ('GR', 'Golden Retriever'), ('GS', 'German Shepard'), ('L', 'Laborador'), ('PT', 'Pointers'), ('P', 'Poodle'), ('R', 'Rottweiler'), ('Y', 'Yorkshire Terrier'), ('A', 'Abyssinian'), ('BN', 'Bengal'), ('DR', 'Devon Rex'), ('H', 'Himalayan'), ('MC', 'Maine Coon'), ('PR', 'Persian'), ('RD', 'Ragdoll'), ('SH', 'Shorthairs'), ('S', 'Siamese'), ('SP', 'Sphynx'), ('M', 'Mixed Breed'), ('O', 'Other'), ('UN', 'Unknown')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disposition',
            field=models.CharField(choices=[('C', 'Good with Children'), ('OA', 'Good with Other Animals'), ('L', 'Animal must be leashed at all times'), ('NA', 'Not Applicable')], default='N/A', max_length=2),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
    ]
