# Generated by Django 3.0.2 on 2020-01-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20200121_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
