# Generated by Django 3.0.2 on 2020-01-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_auto_20200123_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available'), ('P', 'Pending'), ('AD', 'Adopted')], default='A', max_length=2),
        ),
    ]
