# Generated by Django 3.0.2 on 2020-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_auto_20200124_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('B', 'Beagle'), ('FB', 'French Bulldog'), ('GR', 'Golden Retriever'), ('GS', 'German Shepard'), ('L', 'Laborador')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disposition',
            field=models.CharField(choices=[('C', 'Good with Children'), ('OA', 'Good with Other Animals'), ('L', 'Animal must be leashed at all times'), ('NA', 'Not Applicable')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other')], default='D', max_length=2),
        ),
    ]
